name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: curl -s -H "User-Agent:Mozilla/5.0" https://pulsarpolarimetry.streamlit.app/ > /dev/null
