name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install puppeteer
      - run: |
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({ headless: 'new' });
            const page = await browser.newPage();
            await page.goto('https://pulsarpolarimetry.streamlit.app/', { waitUntil: 'networkidle2' });
            await page.waitForTimeout(5000);
            await browser.close();
          })();
          "
